#横方向のStrokeの入力閾値(default: 15)
YawInputBorderDegree: 15
#縦方向のStrokeの入力閾値(default: 11)
PitchInputBorderDegree: 11
#右クリックトグルの動作がおかしい場合に上げる(default: 7)
RightClickHoldOffDelay: 7

MaxStroke: 16
RodMaterial: BLAZE_ROD


Magics:
  JumpPad:
    name: JumpPad
    stroke: ↓↓↑↑
    description: 乗ると高くジャンプ出来るブロックを一定時間展開する.
  SkyWalker:
    name: SkyWalker
    stroke: →←→←
    description: 一定時間足元にブロックが生成され空中を歩くことが出来る.
    radius: 2
  Fireball:
    name: Fireball
    stroke: ↑→←↑
    description: 火の玉を正面に発射する.
  Heal:
    name: Heal
    stroke: ←↑→↓
    description: HPを4回復する.
  Depulso:
    name: Depulso
    stroke: ↑↑↑↑
    description: 目線のエンティティを吹き飛ばす.
    maxDistance: 30
    power: 4
  Accio:
    name: Accio
    stroke: ↓↓↓↓
    description: 目線のエンティティ或いはブロックを目前に引き寄せる.
    maxDistance: 30
  HomenumRevelio:
    name: HomenumRevelio
    stroke: ↑→↓←↑
    description: 周囲のプレイヤーを一時的に発光させる.
    range: 15
    duration: 100
  Freeze:
    name: Freeze
    stroke: ←→←→←→
    description: 目線のエンティティを一時的に凍らせる.
    maxDistance: 30
    duration: 60
  Lightning:
    name: Lightning
    stroke: ↓↓←→
    description: 目線の先に雷を落とす.
    maxDistance: 30
  Teleport:
    name: Teleport
    stroke: ↑↓↑↑
    description: 目線の先にテレポートする.
    maxDistance: 50
